language: python
python:
  - "3.5"
cache: pip
install:
  - pip install awscli
script:
  echo 'script\: what is my purpose?'
  echo 'me\: you satisfy travis build template requirements.'
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: tyler.bacon.io
  skip_cleanup: true
  region: us-west-2
  acl: public_read
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "*"
