language: python
cache: pip
install:
  - pip install awscli
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: tyler.bacon.io
  region: us-west-2
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "*"
